# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter08-APITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chapert08-APITest
  pod 'Alamofire', '~> 5.2'

  # Pods for Chapter08-APITest

end
